apds9960:
  address: 0x39
  update_interval: 10s
  i2c_id: ${apds9960_bus_id}

sensor:
  - platform: apds9960
    type: CLEAR
    name: "Clear"
  - platform: apds9960
    type: PROXIMITY
    name: "Proximity"

binary_sensor:
  - platform: apds9960
    direction: UP
    name: "Up Movement"